"""add_match_videos

Revision ID: 3a94a9b57ea1
Revises: 97aa04b4c7b7
Create Date: 2025-11-23 06:30:07.221458
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a94a9b57ea1'
down_revision: Union[str, None] = '97aa04b4c7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_videos',
    sa.Column('id', sa.Integer(), nullable=False, comment='视频ID'),
    sa.Column('match_id', sa.Integer(), nullable=False, comment='关联的比赛ID'),
    sa.Column('match_game_id', sa.Integer(), nullable=True, comment='关联的小游戏ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='关联选手ID'),
    sa.Column('title', sa.String(), nullable=False, comment='视频标题'),
    sa.Column('url', sa.String(), nullable=False, comment='视频链接'),
    sa.Column('platform', sa.Enum('BILIBILI', 'YOUTUBE', 'TWITCH', 'DOUYU', 'HUYA', 'OTHER', name='videoplatform'), nullable=False, comment='视频平台'),
    sa.Column('video_type', sa.Enum('LIVESTREAM', 'REPLAY', 'HIGHLIGHT', name='videotype'), nullable=True, comment='视频类型'),
    sa.Column('is_official', sa.Boolean(), nullable=True, comment='是否官方录播'),
    sa.Column('uploader_name', sa.String(), nullable=True, comment='上传者名称'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='视频时长(秒)'),
    sa.Column('thumbnail_url', sa.String(), nullable=True, comment='缩略图URL'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='观看次数'),
    sa.Column('description', sa.String(), nullable=True, comment='视频描述'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['match_game_id'], ['match_games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_videos_id'), 'match_videos', ['id'], unique=False)
    op.create_index(op.f('ix_match_videos_is_official'), 'match_videos', ['is_official'], unique=False)
    op.create_index(op.f('ix_match_videos_match_game_id'), 'match_videos', ['match_game_id'], unique=False)
    op.create_index(op.f('ix_match_videos_match_id'), 'match_videos', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_videos_platform'), 'match_videos', ['platform'], unique=False)
    op.create_index(op.f('ix_match_videos_user_id'), 'match_videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_match_videos_video_type'), 'match_videos', ['video_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_videos_video_type'), table_name='match_videos')
    op.drop_index(op.f('ix_match_videos_user_id'), table_name='match_videos')
    op.drop_index(op.f('ix_match_videos_platform'), table_name='match_videos')
    op.drop_index(op.f('ix_match_videos_match_id'), table_name='match_videos')
    op.drop_index(op.f('ix_match_videos_match_game_id'), table_name='match_videos')
    op.drop_index(op.f('ix_match_videos_is_official'), table_name='match_videos')
    op.drop_index(op.f('ix_match_videos_id'), table_name='match_videos')
    op.drop_table('match_videos')
    # ### end Alembic commands ###
