"""init

Revision ID: 4e5c829ddded
Revises: 
Create Date: 2025-11-16 03:17:12.884411
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5c829ddded'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('name', sa.String(), nullable=True, comment='项目名称'),
    sa.Column('code', sa.String(), nullable=True, comment='项目英文代码，用于统一识别相同游戏'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目介绍'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_code'), 'games', ['code'], unique=True)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False, comment='比赛ID'),
    sa.Column('name', sa.String(), nullable=True, comment='比赛名称 (例如：第一届XX杯)'),
    sa.Column('description', sa.String(), nullable=True, comment='比赛描述'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='比赛开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='比赛结束时间'),
    sa.Column('status', sa.Enum('PREPARING', 'ONGOING', 'FINISHED', 'CANCELLED', name='matchstatus'), nullable=True, comment='比赛状态'),
    sa.Column('prize_pool', sa.String(), nullable=True, comment='奖金池'),
    sa.Column('max_teams', sa.Integer(), nullable=True, comment='最大参赛队伍数'),
    sa.Column('max_players_per_team', sa.Integer(), nullable=True, comment='每队最大人数'),
    sa.Column('allow_substitutes', sa.Boolean(), nullable=True, comment='是否允许替补'),
    sa.Column('winning_team_id', sa.Integer(), nullable=True, comment='冠军队伍ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_name'), 'matches', ['name'], unique=False)
    op.create_table('match_teams',
    sa.Column('id', sa.Integer(), nullable=False, comment='比赛队伍ID'),
    sa.Column('match_id', sa.Integer(), nullable=False, comment='关联的比赛ID'),
    sa.Column('name', sa.String(), nullable=False, comment='队伍名称'),
    sa.Column('color', sa.String(), nullable=True, comment='队伍颜色'),
    sa.Column('total_score', sa.Integer(), nullable=True, comment='队伍总积分'),
    sa.Column('games_played', sa.Integer(), nullable=True, comment='已参与游戏数'),
    sa.Column('team_rank', sa.Integer(), nullable=True, comment='队伍排名'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_teams_id'), 'match_teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True, comment='玩家昵称'),
    sa.Column('display_name', sa.String(), nullable=True, comment='显示名称'),
    sa.Column('source', sa.String(), nullable=True, comment='数据来源'),
    sa.Column('total_matches', sa.Integer(), nullable=True, comment='参与比赛总数'),
    sa.Column('total_wins', sa.Integer(), nullable=True, comment='获胜次数'),
    sa.Column('total_points', sa.Integer(), nullable=True, comment='总得分'),
    sa.Column('total_standard_score', sa.Float(), nullable=True, comment='总标准分'),
    sa.Column('average_standard_score', sa.Float(), nullable=True, comment='平均标准分'),
    sa.Column('game_level', sa.String(), nullable=True, comment='游戏等级'),
    sa.Column('level_progress', sa.Float(), nullable=True, comment='等级进度百分比'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.Column('last_active', sa.DateTime(), nullable=True, comment='最后活跃时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_table('match_games',
    sa.Column('id', sa.Integer(), nullable=False, comment='赛程ID'),
    sa.Column('match_id', sa.Integer(), nullable=False, comment='关联的比赛ID'),
    sa.Column('game_id', sa.Integer(), nullable=False, comment='关联的项目ID'),
    sa.Column('game_order', sa.Integer(), nullable=True, comment='比赛顺序'),
    sa.Column('structure_type', sa.String(), nullable=True, comment='对战结构类型'),
    sa.Column('structure_details', sa.JSON(), nullable=True, comment='对战结构详情'),
    sa.Column('multiplier', sa.Float(), nullable=True, comment='游戏积分倍率'),
    sa.Column('is_live', sa.Boolean(), nullable=True, comment='是否正在直播'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='赛程开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='赛程结束时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_games_id'), 'match_games', ['id'], unique=False)
    op.create_table('match_team_memberships',
    sa.Column('id', sa.Integer(), nullable=False, comment='成员关系ID'),
    sa.Column('match_team_id', sa.Integer(), nullable=False, comment='比赛队伍ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.Enum('MAIN', 'SUBSTITUTE', 'CAPTAIN', name='memberrole'), nullable=True, comment='队员角色'),
    sa.Column('joined_at', sa.DateTime(), nullable=True, comment='加入时间'),
    sa.ForeignKeyConstraint(['match_team_id'], ['match_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_team_memberships_id'), 'match_team_memberships', ['id'], unique=False)
    op.create_table('game_lineups',
    sa.Column('id', sa.Integer(), nullable=False, comment='阵容ID'),
    sa.Column('match_game_id', sa.Integer(), nullable=False, comment='赛程ID'),
    sa.Column('match_team_id', sa.Integer(), nullable=False, comment='队伍ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='出战玩家ID'),
    sa.Column('is_starting', sa.Boolean(), nullable=True, comment='是否首发'),
    sa.Column('substitute_reason', sa.String(), nullable=True, comment='替补原因'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['match_game_id'], ['match_games.id'], ),
    sa.ForeignKeyConstraint(['match_team_id'], ['match_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_lineups_id'), 'game_lineups', ['id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False, comment='分数记录ID'),
    sa.Column('points', sa.Integer(), nullable=True, comment='原始得分'),
    sa.Column('standard_score', sa.Float(), nullable=True, comment='标准分（15000分制）'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='得分用户ID'),
    sa.Column('match_team_id', sa.Integer(), nullable=True, comment='得分队伍ID'),
    sa.Column('match_game_id', sa.Integer(), nullable=True, comment='关联的赛程ID'),
    sa.Column('event_data', sa.JSON(), nullable=True, comment='事件详细数据'),
    sa.Column('recorded_at', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.ForeignKeyConstraint(['match_game_id'], ['match_games.id'], ),
    sa.ForeignKeyConstraint(['match_team_id'], ['match_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_game_lineups_id'), table_name='game_lineups')
    op.drop_table('game_lineups')
    op.drop_index(op.f('ix_match_team_memberships_id'), table_name='match_team_memberships')
    op.drop_table('match_team_memberships')
    op.drop_index(op.f('ix_match_games_id'), table_name='match_games')
    op.drop_table('match_games')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_match_teams_id'), table_name='match_teams')
    op.drop_table('match_teams')
    op.drop_index(op.f('ix_matches_name'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_code'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
